#coding:gbk

import threading

DOWNLOAD_URL = "http://mooc.guokr.com"

COURSE_DICT = {
    'Harvard University':0,
    'Berklee College of Music':1,
    'Columbia University':2,
    'California Institute of Technology':3,
    'Duke University':4,
    'Emory University':5,
    'Georgia Institute of Technology':6,
    'Johns Hopkins University':7,
    'Massachusetts Institute of Technology ':8,
    'Princeton University':9,
    'Rice University':10,
    'Stanford University':11,       
    'University of Melbourne':12,
    'University of California, Berkeley':13,
    'University of Pennsylvania':14,
    'University of Rochester':15,
    'University of Michigan':16,
    'University of Virginia':17,
    'Yale University':18,
    'Wesleyan University':19,  
    'Swinburne University':20,    
    'The University of North Carolina at Chapel Hill':21,
    'James Cook University':22,
    'University of California, Irvine':23,
    'Case Western Reserve University':24,   
    'University of Illinois at Urbana-Champaign':25,
    'University of Washington':26,
    'The Hebrew University of Jerusalem': 27,
    'RMIT University':28,  
    'Curtis Institute of Music':29,
    'Universiteit Leiden':30,
    'University of Adelaide':31,
    'University of Wollongong':32,
    'Linux Foundation':33,
    'Mt. San Jacinto College':34,
    'Griffith University':35,
    'University of California, San Diego':36,
    'Macquarie University':37, 
    'University of New Mexico':38,
    'University of Minnesota':39,
    'Yonsei University':40,
    'Delft University of Technology':41,
    'Microsoft':42,
    'IOC Athlete MOOC':43,                       
    '北京大学':44,
    '清华大学':45,
    '复旦大学':46,
    '武汉大学':47,
    '浙江大学':48,
    '南京大学':49,
    '山东大学':50,
    '吉林大学':51,
    '上海交通大学':52,
    '西安交通大学':53,
    '西南交通大学':54,
    '香港大学':55,
    '四川大学':56,
    '湖南大学':57,    
    '中南财经政法大学':58,
    '果壳学院':59,        
    'The Chinese University of Hong Kong':60,
    'The Hong Kong University of Science and Technology':61,
    '國立臺灣大學':62,
    '國立交通大學':63, 
    '國立清華大學':64,               
    'Australian National University':65,
    'Curtin University':66,
    'The University of Queensland':67,
    'Nanyang Technological University':68,
    'The University of Tokyo':69,
    'Tel Aviv University':70,
    'University of Florida':71,
    'University of Copenhagen':72, 
    'others':73
};


PLAT_DICT = {
    'Coursera':0,
    'edX':1,
    '华文慕课':2,
    #'MOOC学院':3,
    #'Udacity':4,
    '学堂在线':3,
    '网易云课堂':4,    
    'OpenLearning':5,
    '中国大学MOOC':6,
    'FutureLearn':7,
    'Open2Study':8, 
    'ewant':9,
    'NovoEd':10,
    '好大学在线':11,
    '果壳学院':12,
    'Udemy':13,
    'Codecademy':14,
    'IOC-Athlete-MOOC':15,
    'gacco':16,
    'iversity':17,
    'others':18      
};